name: Assign new issue to project

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_FOR_ISSUE }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: issueãŒä½œæˆã•ã‚ŒãŸã¨ãã«ã€githubprojectã«è¿½åŠ ã™ã‚‹
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/hgaiji/GithubActions/projects/1'
        column_name: 'ğŸ¤” Considering...'

    - name: ãƒã‚°ãƒ©ãƒ™ãƒ«ã‚’ã¤ã„ãŸissueãŒä½œæˆã•ã‚ŒãŸã¨ãã«TODOã¨ã—ã¦projectã«è¿½åŠ ã™ã‚‹
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/hgaiji/GithubActions/projects/1'
        column_name: 'âœ… To Do'
    # -----------------------------------ã€€slackã¸é€šçŸ¥ ----------------------------------------------------------------
    - name: Slack Notification on Success # ãƒ†ã‚¹ãƒˆæˆåŠŸæ™‚ã¯ã“ã¡ã‚‰ã®ã‚¹ãƒ†ãƒƒãƒ—ãŒå®Ÿè¡Œã•ã‚Œã‚‹
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: issue
        SLACK_TITLE: New Issue Created
        SLACK_COLOR: good
    - name: Slack Notification on Failure # ãƒ†ã‚¹ãƒˆå¤±æ•—æ™‚ã¯ã“ã¡ã‚‰ã®ã‚¹ãƒ†ãƒƒãƒ—ãŒå®Ÿè¡Œã•ã‚Œã‚‹
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_CHANNEL: issue
        SLACK_TITLE: New Issue not Created
        SLACK_COLOR: danger

